import pandas as pd

one_empty = {

'PSCmp':0,
'PSAtt':0,
'PSInc':0,
'PSCmp%':0,
'PSYdsgn':0,
'PSTD':0,
'PSInt':0,
'PSRate':0,
'PSSk':0,
'PSYdsls':0,
'PSY/A':0,
'PSAY/A':0,
'XPM':0,
'XPA':0,
'XP%':0,
'FGM':0,
'FGA':0,
'FG%':0,
'2PM':0,
'Sfty':0,
'SCTD':0,
'SCPts':0,
'RUAtt':0,
'RUYds':0,
'RUY/A':0,
'RUTD':0,
'RETgt':0,
'RERec':0,
'REYds':0,
'REY/R':0,
'RETD':0,
'RECtch%':0,
'REY/Tgt':0,
'KRRt':0,
'KRYds':0,
'KRY/Rt':0,
'KRTD':0,
'PRRet':0,
'PRYds':0,
'PRY/R':0,
'PRTD':0,
'PPnt':0,
'PYds':0,
'PY/P':0,
'PBlck':0,
'TSk':0,
'TSolo':0,
'TAst':0,
'TComb':0,
'TTFL':0,
'TQBHits':0,
'DIInt':0,
'DIYds':0,
'DITD':0,
'DIPD':0,
'FUFmb':0,
'FUFL':0,
'FUFF':0,
'FUFR':0,
'FUYds':0,
'FUTD':0,
'pBlck':0,
'TYTouch':0,
'TYTotOff':0,
'TYYScm':0,
'TYAPYd':0,
'TYRtY':0,
'FFantPt':0,
'FPPR':0,
'FDKPt':0,
'FFDPt':0,
'PSYds':0,

}
print(len(one_empty))

ind = ['PSCmp', 'PSAtt', 'PSInc', 'PSCmp%', 'PSYdsgn', 'PSTD', 'PSInt', 'PSRate', 'PSSk', 'PSYdsls', 'PSY/A', 'PSAY/A', 'XPM', 'XPA', 'XP%', 'FGM', 'FGA', 'FG%', '2PM', 'Sfty', 'SCTD', 'SCPts', 'RUAtt', 'RUYds', 'RUY/A', 'RUTD', 'RETgt', 'RERec', 'REYds', 'REY/R', 'RETD', 'RECtch%', 'REY/Tgt', 'KRRt', 'KRYds', 'KRY/Rt', 'KRTD', 'PRRet', 'PRYds', 'PRY/R', 'PRTD', 'PPnt', 'PYds', 'PY/P', 'PBlck', 'TSk', 'TSolo', 'TAst', 'TComb', 'TTFL', 'TQBHits', 'DIInt', 'DIYds', 'DITD', 'DIPD', 'FUFmb', 'FUFL', 'FUFF', 'FUFR', 'FUYds', 'FUTD', 'pBlck', 'TYTouch', 'TYTotOff', 'TYYScm', 'TYAPYd', 'TYRtY', 'FFantPt', 'FPPR', 'FDKPt', 'FFDPt', 'PSYds']
val = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

ind3 = ['PSAtt_3', 'PSInc_3', 'PSCmp%_3', 'PSYdsgn_3', 'PSTD_3', 'PSInt_3',
       'PSRate_3', 'PSSk_3', 'PSYdsls_3', 'PSY/A_3', 'PSAY/A_3', 'XPM_3',
       'XPA_3', 'XP%_3', 'FGM_3', 'FGA_3', 'FG%_3', '2PM_3', 'Sfty_3',
       'SCTD_3', 'SCPts_3', 'RUAtt_3', 'RUYds_3', 'RUY/A_3', 'RUTD_3',
       'RETgt_3', 'RERec_3', 'REYds_3', 'REY/R_3', 'RETD_3', 'RECtch%_3',
       'REY/Tgt_3', 'KRRt_3', 'KRYds_3', 'KRY/Rt_3', 'KRTD_3', 'PRRet_3',
       'PRYds_3', 'PRY/R_3', 'PRTD_3', 'PPnt_3', 'PYds_3', 'PY/P_3', 'PBlck_3',
       'TSk_3', 'TSolo_3', 'TAst_3', 'TComb_3', 'TTFL_3', 'TQBHits_3',
       'DIInt_3', 'DIYds_3', 'DITD_3', 'DIPD_3', 'FUFmb_3', 'FUFL_3', 'FUFF_3',
       'FUFR_3', 'FUYds_3', 'FUTD_3', 'pBlck_3', 'TYTouch_3', 'TYTotOff_3',
       'TYYScm_3', 'TYAPYd_3', 'TYRtY_3', 'FFantPt_3', 'FPPR_3', 'FDKPt_3',
       'FFDPt_3', 'PSYds_3']

for i in ind:
    sr = i + '_3'
    if sr not in ind3:
        print(i)